### PR TITLE
Markdown preview

### LINKED ISSUE #91: missing a preview mode for markdown-accepting textareas
for the people who don't know markdown by heart (or don't know which markdown flavor this supports and to what extent).

### PR DESCRIPTION
**Pull request by kirushik**
Closes #91

Opens previews in a modal popup window.
Works via javascript and AJAX.
Should be more or less covered by tests (and that coverage is easy to extend in case of bugs).

Currently only bound to Project description form field, but should be pretty easy to attach to other forms/fields as well.

### CODE REVIEW

**Comment by hennevogel** [comment]
Sorry this week was crazy for me. I don't like the interface very much, why don't you put it into a tab? Like in the comment field here. That would be great :-)

**Comment by kirushik** [comment]
@hennevogel OK, I can move that into tab. Will update this PR tommorow, then.

Are you OK with server-side rendering approach in general? I've chosen that over the clientside javascript rendering libraries, mostly because this way we can be as close as possible to the actual rendering outcome.

**Comment by kirushik** [comment]
I will reopen this PR when new interface will be ready.

**Comment by hennevogel** [comment]
@kirushik server side rendering is cool :-)

**Comment by kirushik** [comment]
@hennevogel OK, now there are tabs.

**Comment by hennevogel** [comment]
Me neither. The whole episode handling is not my favourite kind of hack...

**Pull request merged**
