### PR TITLE
Ajaxifying different project tabs

### LINKED ISSUE #111: AJAXifying the main page
We shouldn't really re-render and reload the full page for just switching tabs.
I bet I can implement AJAX calls for those links, which will just replace the contents, not the full webpage.
(And this will certainly work better with the caching from #110 )

### PR DESCRIPTION
**Pull request by namangupta01**
Different project tabs on /projects are made to load via js request Closes #111

### CODE REVIEW

**Comment by namangupta01** [comment]
ezgif com-video-to-gif 6

**Comment by namangupta01** [comment]
Things to do :
- [ ] Push state to change the address
- [ ] Reload page when doing popstate

**Comment by namangupta01** [comment]
Added feature to remember `pushState` history while processing Ajax request.
Pagination links are made Ajax enabled.
Reloading while doing `popState` of page that come from Ajax
All things are shown in gif file.

ezgif com-video-to-gif 7

**Comment by namangupta01** [comment]
@DavidKang @hennevogel Please review.

**Comment by DavidKang** [comment]
@namangupta01, I will try to review it during the week.

**Comment by bgeuken** [comment]
@namangupta01 Looks nice. Though it seems I found a bug:-)

After switching tabs I clicked on the 'grab it' link and got a 500 page because of a ActionController::InvalidAuthenticityToken exception.
 It seems the tabs rendered via ajax are not having the authenticity token added.

I know it's been a while. So if you don't find the time to fix this just let us know. And thanks for working on this in first place:smile:

Appologies for reviewing this so late :blush:

**Comment by bgeuken** [comment]
I added a patch for the csrf token issue.

@DavidKang Please review

**Pull request merged**
