### PR TITLE
Projects can be an array, which need to be decorated differently

### PR DESCRIPTION
**Pull request by bkutil**

### CODE REVIEW

**Comment by kirushik** [comment]
OK, looks good.

I guess we should better write a test for this at some point in the future.

**Comment by bkutil** [comment]
Incomplete. Do not merge yet, please.

**Comment by hennevogel** [comment]
Search is another place where this goes wrong

**Comment by bkutil** [comment]
Ok, should be fixed now.

**Comment by hennevogel** [comment]
deployed

**Pull request merged**
